using BarberBooking.API.Authorization;
using BarberBooking.API.Contracts;
using BarberBooking.API.Contracts.AppointmentContracts;
using BarberBooking.API.Contracts.EmailContracts;
using BarberBooking.API.Contracts.MasterProfileContracts;
using BarberBooking.API.Contracts.MasterTimeSlotContracts;
using BarberBooking.API.Contracts.MasterServicesContracts;
using BarberBooking.API.Contracts.MasterSubscriptionContracts;
using BarberBooking.API.Contracts.MessagesContracts;
using BarberBooking.API.Contracts.ReviewContracts;
using BarberBooking.API.Contracts.SalonPhotosContracts;
using BarberBooking.API.Contracts.SalonsAdminContracts;
using BarberBooking.API.Contracts.SalonsContracts;
using BarberBooking.API.Contracts.TemplateDayContracts;
using BarberBooking.API.Contracts.UserContratcts;
using BarberBooking.API.Contracts.WeeklyTemplateContracts;
using BarberBooking.API.Domain.SalonDomain;
using BarberBooking.API.ExtensionsProject;
using BarberBooking.API.Contracts.FcmPushContracts;
using BarberBooking.API.Infrastructure.Persistence.Repositories;
using BarberBooking.API.Options;
using BarberBooking.API.Messaging.Producer;
using BarberBooking.API.Provider;
using BarberBooking.API.Repositories;
using BarberBooking.API.Service;
using BarberBooking.API.Service.AuthHandler;
using BarberBooking.API.Service.Background;
using BarberBooking.API.Service.Background.Handlers;
using BarberBooking.API.Service.DataService;
using BarberBooking.API.Service.EmailServices;
using BarberBooking.API.Service.MessageService;
using BarberBooking.API.Service.TimeSlotService;
using BarberBooking.API.Service.UpdateService;
using BarberBooking.API.Service.Validator;
using BarberBooking.API.Validator;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using BarberBooking.API.Contracts.ConversationMessagesContracts;
using BarberBooking.API.Contracts.ConversationsContracts;

namespace BarberBooking.API.DependencyInjection;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddApplicationScopedServices(
        this IServiceCollection services,
        IConfiguration configuration)
    {
        services.AddScoped<IPasswordValidatorService, PasswordValidatorService>();
        services.Configure<FirebasePushOptions>(configuration.GetSection(FirebasePushOptions.SectionName));
        services.Configure<AuthorizationOptions>(configuration.GetSection(nameof(AuthorizationOptions)));
        services.AddScoped<IUnitOfWork, UnitOfWork>();
        services.AddScoped<IServicesRepository, ServicesRepository>();
        services.AddScoped<IAppointmentsRepository, AppointmentsRepository>();
        services.AddScoped<IMasterTimeSlotRepository, MasterTimeSlotRepository>();
        services.AddScoped<IUpdateServicesService, UpdateServicesService>();
        services.AddScoped<IUpdateAppointmentService, UpdateAppointmentService>();
        services.AddScoped<IUpdateMasterTimeSlotService, UpdateMasterTimeSlotService>();
        services.AddScoped<IUpdateMasterProfile, UpdateMasterProfile>();
        services.AddScoped<IUpdateSalonService, UpdateSalonService>();
        services.Configure<KafkaProducerSalonSettings>(configuration.GetSection("Kafka"));
        services.AddScoped(typeof(IKafkaProducerSalonEvent<SalonCreatedEvent>), typeof(KafkaProducerSalonEvent<SalonCreatedEvent>));
        services.AddScoped(typeof(IKafkaProducerSalonEvent<SalonDeletedEvent>), typeof(KafkaProducerSalonEvent<SalonDeletedEvent>));
        services.AddScoped(typeof(IKafkaProducerSalonEvent<SalonUpdatedEvent>), typeof(KafkaProducerSalonEvent<SalonUpdatedEvent>));
        services.AddScoped(typeof(IKafkaProducerSalonEvent<SalonAddRatingEvent>), typeof(KafkaProducerSalonEvent<SalonAddRatingEvent>));
        services.AddScoped(typeof(IKafkaProducerSalonEvent<SalonRatingRollbackedEvent>), typeof(KafkaProducerSalonEvent<SalonRatingRollbackedEvent>));
        services.AddKafkaConsumer(configuration);
        services.AddScoped<IJwtProvider, JwtProvider>();
        services.AddScoped<IPermissionsRepository, PermissionsRepository>();
        services.AddScoped<IRolePermissionRepository, RolePermissionRepository>();
        services.AddScoped<IPasswordHasher, PasswordHasher>();
        services.AddScoped<IUserRepository, UsersRepository>();
        services.AddScoped<IUserRolesRepository, UserRolesRepository>();
        services.AddScoped<IMasterSubscriptionRepository, MasterSubscriptionRepository>();
        services.AddScoped<IReviewRepository, ReviewRepository>();
        services.AddScoped<IEmailVerificationRepository, EmailVerificationRepository>();
        services.AddScoped<IEmailService, EmailService>();
        services.AddScoped<IEmailVerficationService, EmailVerificationService>();
        services.AddScoped<IAuthCookieService, AuthCookieService>();
        services.AddScoped<ISalonsRepository, SalonsRepository>();
        services.AddScoped<IMasterProfileRepository, MasterProfileRepository>();
        services.AddScoped<ICacheService, CacheService>();
        services.AddScoped<IUserContext, UserContext>();
        services.AddScoped<ISalonActiveHandler, SalonActiveHandler>();
        services.AddScoped<IEmailVerficationHandler, EmailVerificateDeleteHandler>();
        services.AddScoped<IDnsEmailValidator, DnsEmailValidator>();
        services.AddScoped<IUserValidatorService, UserValidatorService>();
        services.AddScoped<IAppointmentCreationValidator, AppointmentCreationValidator>();
        services.AddScoped<IRatingService, RatingService>();
        services.AddScoped<IEventStoreRepository, EventStoreRepository>();
        services.AddScoped<IRollBackRatingService, RollBackRatingService>();
        services.AddScoped<IRatingCreateSalonService, RatingCreateSalonService>();
        services.AddScoped<IRatingCreateMasterService, RatingCreateMasterService>();
        services.AddScoped<ICityService, CityService>();
        services.AddScoped<IBadWordService, BadWordService>();
        services.AddScoped<IValidateReviewRepository, ValidateReviewRepository>();
        services.AddScoped<IUpdateReviewService, UpdateReviewService>();
        services.AddScoped<IUpdateRatingService, UpdateRatingService>();
        services.AddScoped<IMessagesRepository, MessagesRepository>();
        services.AddScoped<ISalonStatisticRepository, SalonStatisticRepository>();
        services.AddScoped<ISalonStatiscticHandler, SalonStatiscticHandler>();
        services.AddScoped<ISendMessageService, SendMessageService>();
        services.AddScoped<IMessageAppointmentHandler, MessageAppointmentHandler>();
        services.AddScoped<IMasterStatisticRepository, MasterStatisticRepository>();
        services.AddScoped<IMasterStatisticHandler, MasterStatisticHandler>();
        services.AddScoped<IUserFcmTokenRepository, UserFcmTokenRepository>();
        services.AddScoped<IFcmPushService, FcmPushService>();
        services.AddScoped<INotificationService, NotificationService>();
        services.AddScoped<ITimeSlotQualifierBookedService, TimeSlotQualifierBookedService>();
        services.AddScoped<IWeeklyTemplateRepository, WeeklyTemplateRepository>();
        services.AddScoped<ITemplateDayRepository, TemplateDayRepository>();
        services.AddScoped<IMasterServicesRepository, MasterServicesRepository>();
        services.AddScoped<IAutoAppointmentsCancelledHandler, AutoAppointmentsCancelledHandler>();
        services.AddScoped<IAppointmentWithOutUserCreationValidator, AppointmentWithOutUserCreationValidator>();
        services.AddScoped<ISalonsAdminRepository, SalonsAdminRepository>();
        services.AddScoped<AdminSalonAccess>();
        services.AddScoped<ISalonPhotosRepository, SalonPhotosRepository>();
        services.AddScoped<IRefreshTokenService, RefreshTokenService>();
        services.AddScoped<IRefreshTokenRepository, RefreshTokenRepository>();
        services.AddScoped<IGenerateByteArrayService, GenerateByteArrayService>();
        services.AddScoped<IConversationMessagesRepository, ConversationMessagesRepository>();
        services.AddScoped<IConversationsRepository, ConversationsRepository>();
        return services;
    }
}
