name: CI/CD Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ main ]    

jobs:
  test-and-build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Restore & Build & Test
        run: |
          dotnet restore
          dotnet build --configuration Release --no-restore
          dotnet test --no-build --verbosity normal
      - name: Build Docker image (для кэша)
        run: docker build -t barber-api:temp -f BarberBooking.API/Dockerfile .

  deploy-dev:
    needs: test-and-build
    if: github.ref_name == 'develop' && github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: Deploy to Dev
        run: |
          cd ~/project/BarberBooking
          git reset --hard HEAD
          git clean -fd
          git pull origin develop
          docker build -t barber-api:dev -f BarberBooking.API/Dockerfile .
          docker-compose down --remove-orphans
          docker network prune -f
          docker-compose up -d --force-recreate --renew-anon-volumes

  deploy-prod:
    needs: test-and-build
    if: github.ref_name == 'main' && github.event_name == 'push'
    runs-on: self-hosted
    steps:
      - name: Deploy to Prod
        run: |
          cd ~/project/BarberBooking
          git reset --hard HEAD
          git clean -fd
          git pull origin main
          docker build -t barber-api:prod -f BarberBooking.API/Dockerfile .
          docker-compose down --remove-orphans
          docker network prune -f
          docker-compose up -d --force-recreate --renew-anon-volumes